# Disable all post-processing (including HTML minification)
[build.processing]
  skip_processing = true  # This prevents Netlify from modifying your HTML

# Ensure crawling is allowed
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"